### ISSUE TITLE
Cyclic dependencies are a big problem

### ISSUE THREAD

**Issue by karun012** [karun012/arion#14]
After the fix to the transitive dependency issue (#12), I realized that cyclic dependencies will cause a big problem. Should Arion tell the user at startup if there are cyclic dependencies? 
@mwotton @davidsiefert

**Comment by mwotton** [comment]
no, don't think so. you don't need to care, you can just expand the list of modules imported at each step, and stop as soon as the sorted deduped list is the same.

**Comment by karun012** [comment]
@mwotton I think 9db1353 should fix the cyclic dependency problem. Can you also take a look at the fix for transitive check? I'm pretty sure I got the test right this time.
