### ISSUE TITLE
Corruption in output

### ISSUE THREAD

**Issue by karun012** [karun012/arion#16]
Example:

``` shell
Finished in 0.3988 seconds
78 examples, 1 [3 2m  ffacebaooilk.urcom/ge, 1r penodingu ps[0/m
1500213 [2?325h3576734/
```

**Comment by sol** [comment]
I get that a lot too :(

**Comment by karun012** [comment]
@mwotton found the cause :)

I think we can fix it by v0.1.0.8

**Comment by sol** [comment]
yes, please! :)

**Comment by sol** [comment]
Can we have this on hackage please?

**Comment by mwotton** [comment]
I'm still seeing some corruption I think - my patch only removed one obvious source.

**Comment by karun012** [comment]
Very strange. I have tried it on two different machines. I've also used tmux. Haven't seen screen corruption yet.

**Comment by mwotton** [comment]
so, i think the core of it is that there's no locking of stdout - you just shell out. if you make a new MVar, and take it before running a test and put it back after, you should be fine.

**Comment by karun012** [comment]
Okay. I'm reopening the issue.

**Comment by sol** [comment]
Haven't looked at the code in detail, but still I'm puzzled for what reason synchronization is needed.  If I only shell out once at a time and wait for the subprocess to finish before doing anything else, it should be fine, no?

**Comment by mwotton** [comment]
the problem is that the filewatcher spins off new threads for every event.

**Comment by karun012** [comment]
Interesting!

**Comment by karun012** [comment]
Should we push out v0.1.0.8?

@sol @mwotton There were issues with the transitive dependency check. I think I've covered all the cases. We can push v0.1.0.8 out right away.

**Comment by sol** [comment]
@karun012 Yes, new release would be great! :)

@mwotton Would it be possible to prevent the file watcher from doing so?  If not, could we still feed those events back to the main thread by using a `Control.Cocurrent.Chan`?

**Comment by karun012** [comment]
Ha! Alright @sol. It should hit hackage in a few minutes. The transitive dependency check was screwed up in 0.1.0.7 anyway. This should make it better.

**Comment by karun012** [comment]
Sorry @sol. I spoke too soon :) 

We will have v0.1.0.8 in hackage very soon. @mwotton has some more fixes in the works

**Comment by karun012** [comment]
@sol 0.1.0.8 should Hackage in a few minutes!
