### ISSUE TITLE
transitive checking seems wrong

### ISSUE THREAD

**Issue by mwotton** [karun012/arion#19]
I have a module Domain.hs that imports A.hs, B.hs and C.hs. The only thing that imports Domain is DomainSpec.hs

When I change Domain.hs, ASpec.hs etc get run as well.

**Comment by karun012** [comment]
Ah. Yes. The test was wrong. I'll try and get a fix in ASAP.

**Comment by karun012** [comment]
@mwotton can you review the fix when you have a minute? I reopened it.

**Comment by karun012** [comment]
I think we should get this fix out soon. I should not have pushed out v0.1.0.7 :(
