### ISSUE TITLE
if a source file has no dependencies, we should probably flag the fact

### ISSUE THREAD

**Issue by mwotton** [karun012/arion#21]
it's useful information that a file is completely untested :)

**Comment by mwotton** [comment]
uh, reverse dependencies, i mean. IE, no test file.

**Comment by karun012** [comment]
Should say something like...

**What are you doing with Foo.hs? Really!** :grin: 

Yeah. I think it is useful information.

**Comment by karun012** [comment]
@mwotton :+1:?

**Comment by mwotton** [comment]
looks good

**Comment by karun012** [comment]
Got to get more attention to this :) Need users
