### ISSUE TITLE
allow spec helper files

### ISSUE THREAD

**Issue by mwotton** [karun012/arion#7]
In my projects I usually have a spec helper sitting in test/SpecHelper.hs for commonly used test helpers.
Arion doesn't seem to see them:

```
/home/mark/projects/meanpath/Perspective/test/Net/Perspective/Domain/LinkedInSpec.hs:8:18:
    Could not find module ‘SpecHelper’
    Use -v to see a list of the files searched for.
```

cabal build/cabal test works fine.

**Comment by karun012** [comment]
I've pushed a fix. If you need it immediately, I can bump the version and release it to Hackage. Let me know.

**Comment by mwotton** [comment]
thanks, that works (modulo the other issue i logged). Quick work, thank you!

**Comment by mwotton** [comment]
(no need to bump till you're ready, i can run from a local copy.)

**Comment by karun012** [comment]
That was a good catch. I have rarely used spec helpers. I will bump it in a couple of days. I really feel that it makes the tool look bad :)
